### ISSUE TITLE
It seems not working with Angular AoT

### ISSUE THREAD

**Issue by CrisDan1905** [dundalek/latinize#10]
Hello. I have an Angular 4 project which I'm using Latinize and it doesn't seem to work with the AoT compiling system. I've been following te Angular official guide: [https://angular.io/guide/aot-compiler](url) and trying this command:
`node_modules/.bin/ngc -p tsconfig-aot.json`, however I get this error due latinize:

`Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/danilo/Proyectos/krgo/frontend/node_modules/angular2latinize/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /home/danilo/Proyectos/krgo/frontend/node_modules/angular2latinize/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /home/danilo/Proyectos/krgo/frontend/node_modules/angular2latinize/node_modules/@angular/core/src/di/opaque_token.d.ts`

so I can't change the way Angular compiles and I really need to do it. How can I solve this please??

**Comment by dundalek** [comment]
Hi, you use a different package: https://github.com/luckylooke/angular2latinize
