### ISSUE TITLE
Bower.json has incorrect main file name

### ISSUE THREAD

**Issue by pilaas** [dundalek/latinize#4]
There is no ```latinize-amd.js``` file in project directory.

**Comment by dundalek** [comment]
The `latinize` bower package is published by [someone else](https://github.com/rs3d/latinize). I've contacted the author about it. In the meantime you can use `latinizejs` which should work correctly.

**Comment by dundalek** [comment]
You can use `latinize` now. Thanks to Robin @rs3d
