### ISSUE TITLE
TS support

### ISSUE THREAD

**Issue by Ibydy** [dundalek/latinize#5]
please , make support for typescript.There is a problem, in your export

**Comment by dundalek** [comment]
Hi, I don't use TS, can you verify if [this definition](https://www.npmjs.com/package/@types/latinize) works for you?

**Comment by 1000i100** [comment]
does the #12 pull request have a typescript compatible syntax ?

**Comment by dundalek** [comment]
Closing since I did not get a response of what is not working.
